CREATE TABLE [Equipment].[Equipments] (
    [Id]                            INT            IDENTITY (1, 1) NOT NULL,
    [Name]                          NVARCHAR (MAX) NULL,
    [Tag]                           NVARCHAR (MAX) NULL,
    [EquipmentLookupId]             INT            NOT NULL,
    [HealthFacilityId]              INT            NOT NULL,
    [OwnerId]                       INT            NOT NULL,
    [SerialNumber]                  NVARCHAR (100) NULL,
    [EquipmentStatusId]             INT            NULL,
    [InstalledDate]                 DATETIME2 (7)  NULL,
    [InstalledBy]                   NVARCHAR (MAX) NULL,
    [ManufactureDate]               DATETIME2 (7)  NULL,
    [EquipmentStatus]               INT            NULL,
    [Make]                          NVARCHAR (300) NULL,
    [Model]                         NVARCHAR (300) NULL,
    [ChasisNo]                      NVARCHAR (300) NULL,
    [StartKMReading]                INT            NULL,
    [LastPreventiveMaintenanceDate] DATETIME2 (7)  NULL,
    [NumberOfHoursWorked]           INT            NULL,
    [FuelConsumption]               INT            NULL,
    [PlateNo]                       NVARCHAR (300) NULL,
    [AssignedDriver]                NVARCHAR (300) NULL,
    [IsDeleted]                     BIT            CONSTRAINT [DF__Equipment__IsDel__19DFD96B] DEFAULT (CONVERT([bit],(0))) NULL,
    [IsActive]                      BIT            CONSTRAINT [DF__Equipment__IsAct__1AD3FDA4] DEFAULT (CONVERT([bit],(0))) NULL,
    [CreatedBy]                     INT            NULL,
    [CreatedOn]                     DATETIME2 (7)  NULL,
    [UpdatedBy]                     INT            NULL,
    [UpdatedOn]                     DATETIME2 (7)  NULL,
    CONSTRAINT [PK_Equipments] PRIMARY KEY CLUSTERED ([Id] ASC)
);

