CREATE TABLE [Security].[Users] (
    [Id]                     INT                IDENTITY (1, 1) NOT NULL,
    [CustomerID]             INT                NULL,
    [FirstName]              NVARCHAR (MAX)     NULL,
    [LastName]               NVARCHAR (MAX)     NULL,
    [Address]                NVARCHAR (MAX)     NULL,
    [PersonalImagePath]      NVARCHAR (MAX)     NULL,
    [Education]              NVARCHAR (MAX)     NULL,
    [Experience]             NVARCHAR (MAX)     NULL,
    [Specialties]            NVARCHAR (MAX)     NULL,
    [HealthFacilityId]       INT                NULL,
    [IP]                     NVARCHAR (MAX)     NULL,
    [ChangePassword]         BIT                DEFAULT (CONVERT([bit],(0))) NOT NULL,
    [CallingCode]            NVARCHAR (MAX)     NULL,
    [CreatedBy]              INT                NULL,
    [CreatedOn]              DATETIME2 (7)      NOT NULL,
    [UpdatedBy]              INT                NULL,
    [UpdatedOn]              DATETIME2 (7)      NULL,
    [Status]                 NVARCHAR (MAX)     NULL,
    [NextPasswordExpiryDate] DATETIME2 (7)      NOT NULL,
    [EmailVerifiedDate]      DATETIME2 (7)      NULL,
    [UserName]               NVARCHAR (256)     NULL,
    [NormalizedUserName]     NVARCHAR (256)     NULL,
    [Email]                  NVARCHAR (256)     NULL,
    [NormalizedEmail]        NVARCHAR (256)     NULL,
    [EmailConfirmed]         BIT                DEFAULT (CONVERT([bit],(0))) NOT NULL,
    [PasswordHash]           NVARCHAR (MAX)     NULL,
    [SecurityStamp]          NVARCHAR (MAX)     NULL,
    [ConcurrencyStamp]       NVARCHAR (MAX)     NULL,
    [PhoneNumber]            NVARCHAR (MAX)     NULL,
    [PhoneNumberConfirmed]   BIT                DEFAULT (CONVERT([bit],(0))) NOT NULL,
    [TwoFactorEnabled]       BIT                DEFAULT (CONVERT([bit],(0))) NOT NULL,
    [LockoutEnd]             DATETIMEOFFSET (7) NULL,
    [LockoutEnabled]         BIT                DEFAULT (CONVERT([bit],(0))) NOT NULL,
    [AccessFailedCount]      INT                NOT NULL,
    CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Users_Customers_CustomerID] FOREIGN KEY ([CustomerID]) REFERENCES [Subscription].[Customers] ([Id]),
    CONSTRAINT [FK_Users_HealthFacilities_HealthFacilityId] FOREIGN KEY ([HealthFacilityId]) REFERENCES [Metadata].[HealthFacilities] ([Id])
);

