CREATE TABLE [Security].[UserTransactionHistories] (
    [Id]                     INT            IDENTITY (1, 1) NOT NULL,
    [UserId]                 INT            NOT NULL,
    [Description]            NVARCHAR (MAX) NULL,
    [From]                   NVARCHAR (MAX) NULL,
    [To]                     NVARCHAR (MAX) NULL,
    [UserTransactionTypeId]  INT            NOT NULL,
    [Location_IP]            NVARCHAR (MAX) NULL,
    [Location_City]          NVARCHAR (MAX) NULL,
    [Location_Region]        NVARCHAR (MAX) NULL,
    [Location_RegionCode]    NVARCHAR (MAX) NULL,
    [Location_CountryName]   NVARCHAR (MAX) NULL,
    [Location_CountryCode]   NVARCHAR (MAX) NULL,
    [Location_ContinentName] NVARCHAR (MAX) NULL,
    [Location_ContinentCode] NVARCHAR (MAX) NULL,
    [Location_Latitude]      REAL           NULL,
    [Location_Longitude]     REAL           NULL,
    [Location_ASN]           NVARCHAR (MAX) NULL,
    [Location_Flag]          NVARCHAR (MAX) NULL,
    [Location_Postal]        NVARCHAR (MAX) NULL,
    [Location_CallingCode]   NVARCHAR (MAX) NULL,
    [Location_RTL]           BIT            DEFAULT (CONVERT([bit],(0))) NULL,
    [IsDeleted]              BIT            DEFAULT (CONVERT([bit],(0))) NOT NULL,
    [IsActive]               BIT            DEFAULT (CONVERT([bit],(0))) NOT NULL,
    [CreatedBy]              INT            NULL,
    [CreatedOn]              DATETIME2 (7)  NOT NULL,
    [UpdatedBy]              INT            NULL,
    [UpdatedOn]              DATETIME2 (7)  NULL,
    CONSTRAINT [PK_UserTransactionHistories] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_UserTransactionHistories_Users_CreatedBy] FOREIGN KEY ([CreatedBy]) REFERENCES [Security].[Users] ([Id]),
    CONSTRAINT [FK_UserTransactionHistories_Users_UpdatedBy] FOREIGN KEY ([UpdatedBy]) REFERENCES [Security].[Users] ([Id]),
    CONSTRAINT [FK_UserTransactionHistories_Users_UserId] FOREIGN KEY ([UserId]) REFERENCES [Security].[Users] ([Id]),
    CONSTRAINT [FK_UserTransactionHistories_UserTransactionTypes_UserTransactionTypeId] FOREIGN KEY ([UserTransactionTypeId]) REFERENCES [Metadata].[UserTransactionTypes] ([Id])
);

