CREATE TABLE [Maintenance].[WorkOrders] (
    [Id]                 INT            IDENTITY (1, 1) NOT NULL,
    [Title]              NVARCHAR (MAX) NULL,
    [PlannedStartDate]   NVARCHAR (MAX) NULL,
    [PlannedEndDate]     NVARCHAR (MAX) NULL,
    [StartTime]          NVARCHAR (50)  NULL,
    [EndTime]            NVARCHAR (50)  NULL,
    [Description]        NVARCHAR (MAX) NULL,
    [MaintenanceHeadId]  INT            NULL,
    [ForwardedFromId]    INT            NULL,
    [WorkOrderHeaderId]  INT            NOT NULL,
    [ContractorId]       INT            NULL,
    [AssignedEngineerId] INT            NULL,
    [ManagerPriorityId]  INT            NULL,
    [IsDeleted]          BIT            CONSTRAINT [DF__WorkOrder__IsDel__58D1301D] DEFAULT (CONVERT([bit],(0))) NOT NULL,
    [IsActive]           BIT            CONSTRAINT [DF__WorkOrder__IsAct__59C55456] DEFAULT (CONVERT([bit],(0))) NOT NULL,
    [CreatedBy]          INT            NULL,
    [CreatedOn]          DATETIME2 (7)  NOT NULL,
    [UpdatedBy]          INT            NULL,
    [UpdatedOn]          DATETIME2 (7)  NULL,
    [OfflineContractor]  NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_WorkOrders] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_WorkOrders_Customers_ContractorId] FOREIGN KEY ([ContractorId]) REFERENCES [Subscription].[Customers] ([Id]),
    CONSTRAINT [FK_WorkOrders_Customers_ForwardedFromId] FOREIGN KEY ([ForwardedFromId]) REFERENCES [Subscription].[Customers] ([Id]),
    CONSTRAINT [FK_WorkOrders_Priority_ManagerPriorityId] FOREIGN KEY ([ManagerPriorityId]) REFERENCES [Maintenance].[Priority] ([Id]),
    CONSTRAINT [FK_WorkOrders_Users_AssignedEngineerId] FOREIGN KEY ([AssignedEngineerId]) REFERENCES [Security].[Users] ([Id]),
    CONSTRAINT [FK_WorkOrders_Users_CreatedBy] FOREIGN KEY ([CreatedBy]) REFERENCES [Security].[Users] ([Id]),
    CONSTRAINT [FK_WorkOrders_Users_MaintenanceHeadId] FOREIGN KEY ([MaintenanceHeadId]) REFERENCES [Security].[Users] ([Id]),
    CONSTRAINT [FK_WorkOrders_Users_UpdatedBy] FOREIGN KEY ([UpdatedBy]) REFERENCES [Security].[Users] ([Id]),
    CONSTRAINT [FK_WorkOrders_WorkOrderHeader_WorkOrderHeaderId] FOREIGN KEY ([WorkOrderHeaderId]) REFERENCES [Maintenance].[WorkOrderHeader] ([Id])
);

